### PR TITLE
English version

### PR DESCRIPTION
**Pull request by Finalcreature**
I added an alternative language change for the app.

I used react-i18next library to achieve this.

Notes:

1.The language change button currently has two modes: Hebrew and English.
2. If you want to add more languages in the future, the button can be changed to cycle through them or replaced with a dropdown.
3. I can create a new component (e.g. ToggleLanguage.tsx) for the language change button if you want.
4. I originally planned to use the ToggleSwitch component, but it would require too many changes. If you have a better solution, I'm happy to hear it.

### CODE REVIEW

**Comment by develad** [comment]
Please Resolve conflicts

**Comment by develad** [comment]
Hi Nadav !!

**Thanks again for the awesome work!**

I've looked in this pull-request and noticed some thing that requiring some fixing to do

- The styling is off on mobile view (iPhone x). The flag is on top of the toggle button
- The text direction is not correct when switching into English (ex: milk x 1)
- The Modal component language doesn't change from Hebrew to English

Care to fix the bugs?

Cheers 🍻

Screenshots:
localhost_5173_cart_(iPhone X) (2)
localhost_5173_cart_(iPhone X) (1)

**Comment by Finalcreature** [comment]
PR is ready for review

**Comment by develad** [comment]
Hi Nadav

Please review the style. Do like the the new Hebrew/English button?

**Comment by Finalcreature** [comment]
I like it. Just FYI, once you decided (if you do) to add a 3rd language a switch wouldn't be suitable.

**Comment by develad** [comment]
Thank you Nadav!
For the meanwhile I think this Hebrew/English toggle button will do the job (unless this site will become a multi billion gazillion dollar unicorn the we'll need to change it to a select between languages 😃) 

Happy Merging !

**Pull request merged**
