### PR TITLE
functionally working

### PR DESCRIPTION
**Pull request by Finalcreature**
I wanted to contribute this feature which allows the user to edit an item from the list after adding it.

Currently, the user can edit items that are already checked, so if you want, I can prevent it from happening if you like.

### CODE REVIEW

**Comment by develad** [comment]
Hi Nadav!! 

First of all **I LOVE ALL THE WORK (!)** you've put in all the pull requests you've made! Thank you! 

About this one I found a few bugs. I attached screenshot to make more clear:

1. The form is staying on "isEditing" mode if the user is deleting the list while he is on editing mode ( Edit -> Delete list ) 
2. The site is mobile responsive. The buttons should be on top of each other. You need to use different break points on the various elements in different screen sizes [https://tailwindcss.com/docs/responsive-design](https://tailwindcss.com/docs/responsive-design)
3. On mobile view the edit button is hiding completely the trash button 


I have few suggestions for next features that could be implemented in this branch scope, such as: 

-   Implement a deletion of a specific item from the items list WHILE in editing mode
-  Making the UI more noticeable for the user when he/she is editing (Maybe a Red border around the item that is being edited ?!)

Would you like to fix the bugs so I can merge this branch to the main branch?

Anyway as I said I really appreciate your contribution to the project 🤘😺

Screenshots:
 
localhost_5174_cart_ (1)
localhost_5174_cart_
localhost_5174_cart_(iPhone X)

**Comment by Finalcreature** [comment]
Thank you for the feedback.

I'll fix everything (including the stuff from my other PR) and commit again.

**Comment by Finalcreature** [comment]
I fixed the bugs. 

I will work on the suggested features once I fix the bugs on the other branch. 

Btw, currently the edited item is marked with an orange circle next to it. Regardless, I can change it to a more noticeable marker like you suggested.

**Comment by Finalcreature** [comment]
PR is ready for review.

Notes:

1. I added the desired features.

2. Hope you liked my improved UI for the editing mode.

Please let me know if there are any other features you have in mind that I can work on 😇

**Comment by develad** [comment]
> PR is ready for review.
> 
> Notes:
> 
> 1. I added the desired features.
> 2. Hope you liked my improved UI for the editing mode.
> 
> Please let me know if there are any other features you have in mind that I can work on 😇


Hi Nadav,

**I love all the work you have done!!!**
Unfortunately, there is still a bug left in this version, If all the items are checked in the list (All done) and the user is deleting the list with the Trash button the form is going into edit mode
  
Screenshots:
 
pr-1

**Comment by Finalcreature** [comment]
Bug is fixed.

Note:

I changed   `setIsEditing(shouldKeepEditing || !isEditing);`

to

```
 setIsEditing(
      typeof shouldKeepEditing === "boolean" ? shouldKeepEditing : !isEditing
    );
``` 

which should result the same when   `shouldKeepEditing ===  undifined `


but it seems it sets `!isEditing` when `shouldKeepEditing` is false.

Do you have any idea why?

**Comment by develad** [comment]
Hi Nadav,

I've reviewed the updates that you've made. Its working(!) … but I think there is a better way than doing a typeof check to solve it.
Note that in EditBtn.tsx you're invoking the handleEditList function with an empty object (Why?!)

**Comment by Finalcreature** [comment]
I replaced the typeof to undifined now - I can't check use the following

``` const handleEditList = (shouldKeepEditing?: boolean) => {
    setIsEditing(
      shouldKeepEditing ? shouldKeepEditing : !isEditing
    );
    setEditItem(null);
  }; 
```

because it will end up with the else statement when `shouldKeepEditing ` is `false` or `undifined`. 
I hope you find it more suitable than `typeof`

--------------------------------------------------------------------------------------------------------------------------------

I wanted `handleEditList` to have an optional object which has a key of `shouldKeepEditing` in a way that when I invoke it from a different component instead of just passing a `boolean` (e.g `handleEditList(false)`) I could pass a named argument (e.g `handleEditList({shouldKeepEditing: false)`) which in my opinion is more informative.

However, when I set the function interface to this:

```
interface editProps {
  handleEditList: ({
    shouldKeepEditing,
  }: {
    shouldKeepEditing?: boolean;
  }) => void;
}
```

it forced me to send at least an empty object. 

I also tried changing it to:

```
interface editProps {
  handleEditList: (shouldKeepEditing?: {
    shouldKeepEditing: boolean
  }) => void;
}
```
but that would have forced me destruct/chain it in the declared function:

e.g:

```
 const handleEditList = (shouldKeepEditing) => {
    setIsEditing(
      shouldKeepEditing.shouldKeepEditing !== undefined ? shouldKeepEditing : !isEditing
    );
    setEditItem(null);
  };
```

which I didn't find as a good practice.

So you can see what I opt for the current solution.

**Pull request merged**
